//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.DTO.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.DTO.Orders.OrderValidationMessages", typeof(OrderValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be between {1} and {2}..
        /// </summary>
        public static string InvalidPriceRange {
            get {
                return ResourceManager.GetString("InvalidPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid zip code format..
        /// </summary>
        public static string InvalidZipCode {
            get {
                return ResourceManager.GetString("InvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthBasketId {
            get {
                return ResourceManager.GetString("MaxLengthBasketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthCity {
            get {
                return ResourceManager.GetString("MaxLengthCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be longer than {1} characters..
        /// </summary>
        public static string MaxLengthDeliveryTime {
            get {
                return ResourceManager.GetString("MaxLengthDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be longer than {1} characters..
        /// </summary>
        public static string MaxLengthDescription {
            get {
                return ResourceManager.GetString("MaxLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthFirstName {
            get {
                return ResourceManager.GetString("MaxLengthFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthLastName {
            get {
                return ResourceManager.GetString("MaxLengthLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be longer than {1} characters..
        /// </summary>
        public static string MaxLengthName {
            get {
                return ResourceManager.GetString("MaxLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthState {
            get {
                return ResourceManager.GetString("MaxLengthState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthStreet {
            get {
                return ResourceManager.GetString("MaxLengthStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket ID is required..
        /// </summary>
        public static string RequiredBasketId {
            get {
                return ResourceManager.GetString("RequiredBasketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string RequiredCity {
            get {
                return ResourceManager.GetString("RequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method ID is required..
        /// </summary>
        public static string RequiredDeliveryMethodId {
            get {
                return ResourceManager.GetString("RequiredDeliveryMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery time is required..
        /// </summary>
        public static string RequiredDeliveryTime {
            get {
                return ResourceManager.GetString("RequiredDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string RequiredFirstName {
            get {
                return ResourceManager.GetString("RequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string RequiredLastName {
            get {
                return ResourceManager.GetString("RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address is required..
        /// </summary>
        public static string RequiredShippingAddress {
            get {
                return ResourceManager.GetString("RequiredShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required..
        /// </summary>
        public static string RequiredState {
            get {
                return ResourceManager.GetString("RequiredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is required..
        /// </summary>
        public static string RequiredStreet {
            get {
                return ResourceManager.GetString("RequiredStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code is required..
        /// </summary>
        public static string RequiredZipCode {
            get {
                return ResourceManager.GetString("RequiredZipCode", resourceCulture);
            }
        }
    }
}
