//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.Services.Discounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiscountService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiscountService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.Services.Discounts.DiscountService", typeof(DiscountService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active discounts retrieved successfully..
        /// </summary>
        public static string ActiveDiscountsRetrieved {
            get {
                return ResourceManager.GetString("ActiveDiscountsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than start date..
        /// </summary>
        public static string DateRangeError {
            get {
                return ResourceManager.GetString("DateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount activated successfully..
        /// </summary>
        public static string DiscountActivated {
            get {
                return ResourceManager.GetString("DiscountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount applied successfully..
        /// </summary>
        public static string DiscountApplied {
            get {
                return ResourceManager.GetString("DiscountApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount code is valid..
        /// </summary>
        public static string DiscountCodeValid {
            get {
                return ResourceManager.GetString("DiscountCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount created successfully..
        /// </summary>
        public static string DiscountCreated {
            get {
                return ResourceManager.GetString("DiscountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount dates updated successfully..
        /// </summary>
        public static string DiscountDatesUpdated {
            get {
                return ResourceManager.GetString("DiscountDatesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount deleted successfully..
        /// </summary>
        public static string DiscountDeleted {
            get {
                return ResourceManager.GetString("DiscountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount expired successfully..
        /// </summary>
        public static string DiscountExpired {
            get {
                return ResourceManager.GetString("DiscountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount code is not active..
        /// </summary>
        public static string DiscountNotActive {
            get {
                return ResourceManager.GetString("DiscountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount not found..
        /// </summary>
        public static string DiscountNotFound {
            get {
                return ResourceManager.GetString("DiscountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount not valid for this brand..
        /// </summary>
        public static string DiscountNotValidBrand {
            get {
                return ResourceManager.GetString("DiscountNotValidBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount not valid for this category..
        /// </summary>
        public static string DiscountNotValidCategory {
            get {
                return ResourceManager.GetString("DiscountNotValidCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount not valid for this product..
        /// </summary>
        public static string DiscountNotValidProduct {
            get {
                return ResourceManager.GetString("DiscountNotValidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount retrieved successfully..
        /// </summary>
        public static string DiscountRetrieved {
            get {
                return ResourceManager.GetString("DiscountRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts retrieved successfully..
        /// </summary>
        public static string DiscountsRetrieved {
            get {
                return ResourceManager.GetString("DiscountsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount updated successfully..
        /// </summary>
        public static string DiscountUpdated {
            get {
                return ResourceManager.GetString("DiscountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired discounts retrieved successfully..
        /// </summary>
        public static string ExpiredDiscountsRetrieved {
            get {
                return ResourceManager.GetString("ExpiredDiscountsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or inactive discount code..
        /// </summary>
        public static string InvalidDiscountCode {
            get {
                return ResourceManager.GetString("InvalidDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming discounts retrieved successfully..
        /// </summary>
        public static string UpcomingDiscountsRetrieved {
            get {
                return ResourceManager.GetString("UpcomingDiscountsRetrieved", resourceCulture);
            }
        }
    }
}
