//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.Services.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.Services.Account.AuthenticationService", typeof(AuthenticationService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is invalid..
        /// </summary>
        public static string AccessTokenInvalid {
            get {
                return ResourceManager.GetString("AccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already confirmed..
        /// </summary>
        public static string AccountAlreadyConfirmed {
            get {
                return ResourceManager.GetString("AccountAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully..
        /// </summary>
        public static string AccountDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AccountDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is temporarily locked due to multiple failed login attempts. Please try again later..
        /// </summary>
        public static string AccountLockedOut {
            get {
                return ResourceManager.GetString("AccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email resent successfully..
        /// </summary>
        public static string ConfirmationEmailResentSuccessfully {
            get {
                return ResourceManager.GetString("ConfirmationEmailResentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email already sent recently. Please wait before requesting again..
        /// </summary>
        public static string ConfirmationEmailSentRecently {
            get {
                return ResourceManager.GetString("ConfirmationEmailSentRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email before linking an external login..
        /// </summary>
        public static string ConfirmEmailBeforeLinking {
            get {
                return ResourceManager.GetString("ConfirmEmailBeforeLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must confirm your email before logging in..
        /// </summary>
        public static string ConfirmEmailBeforeLogin {
            get {
                return ResourceManager.GetString("ConfirmEmailBeforeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email before resetting password..
        /// </summary>
        public static string ConfirmEmailBeforeReset {
            get {
                return ResourceManager.GetString("ConfirmEmailBeforeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already confirmed..
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        public static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered..
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email claim is missing in token..
        /// </summary>
        public static string EmailClaimMissing {
            get {
                return ResourceManager.GetString("EmailClaimMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed successfully..
        /// </summary>
        public static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed..
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with this email..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External provider error: {0}.
        /// </summary>
        public static string ExternalProviderError {
            get {
                return ResourceManager.GetString("ExternalProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External provider did not supply email or username..
        /// </summary>
        public static string ExternalProviderMissingIdentityData {
            get {
                return ResourceManager.GetString("ExternalProviderMissingIdentityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password..
        /// </summary>
        public static string FailedToChangePassword {
            get {
                return ResourceManager.GetString("FailedToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to confirm email..
        /// </summary>
        public static string FailedToConfirmEmail {
            get {
                return ResourceManager.GetString("FailedToConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create account from external login..
        /// </summary>
        public static string FailedToCreateAccountFromExternal {
            get {
                return ResourceManager.GetString("FailedToCreateAccountFromExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account..
        /// </summary>
        public static string FailedToDeleteAccount {
            get {
                return ResourceManager.GetString("FailedToDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to link external login..
        /// </summary>
        public static string FailedToLinkExternalLogin {
            get {
                return ResourceManager.GetString("FailedToLinkExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to link external provider to existing account..
        /// </summary>
        public static string FailedToLinkExternalProvider {
            get {
                return ResourceManager.GetString("FailedToLinkExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load external login info..
        /// </summary>
        public static string FailedToLoadExternalLoginInfo {
            get {
                return ResourceManager.GetString("FailedToLoadExternalLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password..
        /// </summary>
        public static string FailedToResetPassword {
            get {
                return ResourceManager.GetString("FailedToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update profile..
        /// </summary>
        public static string FailedToUpdateProfile {
            get {
                return ResourceManager.GetString("FailedToUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user after confirmation..
        /// </summary>
        public static string FailedToUpdateUserAfterConfirmation {
            get {
                return ResourceManager.GetString("FailedToUpdateUserAfterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size exceeds limit..
        /// </summary>
        public static string ImageSizeExceedsLimit {
            get {
                return ResourceManager.GetString("ImageSizeExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email..
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired confirmation token..
        /// </summary>
        public static string InvalidConfirmationToken {
            get {
                return ResourceManager.GetString("InvalidConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type..
        /// </summary>
        public static string InvalidImageType {
            get {
                return ResourceManager.GetString("InvalidImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login data..
        /// </summary>
        public static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired token..
        /// </summary>
        public static string InvalidOrExpiredToken {
            get {
                return ResourceManager.GetString("InvalidOrExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration data..
        /// </summary>
        public static string InvalidRegistrationData {
            get {
                return ResourceManager.GetString("InvalidRegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reset password data..
        /// </summary>
        public static string InvalidResetPasswordData {
            get {
                return ResourceManager.GetString("InvalidResetPasswordData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token format..
        /// </summary>
        public static string InvalidTokenFormat {
            get {
                return ResourceManager.GetString("InvalidTokenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token model..
        /// </summary>
        public static string InvalidTokenModel {
            get {
                return ResourceManager.GetString("InvalidTokenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid update data..
        /// </summary>
        public static string InvalidUpdateData {
            get {
                return ResourceManager.GetString("InvalidUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification request..
        /// </summary>
        public static string InvalidVerificationRequest {
            get {
                return ResourceManager.GetString("InvalidVerificationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        public static string LoggedOutSuccessfully {
            get {
                return ResourceManager.GetString("LoggedOutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login data cannot be null..
        /// </summary>
        public static string LoginDataRequired {
            get {
                return ResourceManager.GetString("LoginDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not allowed to login..
        /// </summary>
        public static string LoginNotAllowed {
            get {
                return ResourceManager.GetString("LoginNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found for the provided user ID..
        /// </summary>
        public static string NoAccountForUserId {
            get {
                return ResourceManager.GetString("NoAccountForUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file provided..
        /// </summary>
        public static string NoFileProvided {
            get {
                return ResourceManager.GetString("NoFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset link has been sent to your email..
        /// </summary>
        public static string PasswordResetLinkSent {
            get {
                return ResourceManager.GetString("PasswordResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset email was already sent recently. Please wait before trying again..
        /// </summary>
        public static string PasswordResetSentRecently {
            get {
                return ResourceManager.GetString("PasswordResetSentRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        public static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is invalid or expired..
        /// </summary>
        public static string RefreshTokenInvalidOrExpired {
            get {
                return ResourceManager.GetString("RefreshTokenInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration data cannot be null..
        /// </summary>
        public static string RegistrationDataRequired {
            get {
                return ResourceManager.GetString("RegistrationDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed..
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please check your email to confirm your account..
        /// </summary>
        public static string RegistrationSuccessfulConfirmEmail {
            get {
                return ResourceManager.GetString("RegistrationSuccessfulConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body cannot be null..
        /// </summary>
        public static string RequestBodyRequired {
            get {
                return ResourceManager.GetString("RequestBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset already requested..
        /// </summary>
        public static string ResetAlreadyRequested {
            get {
                return ResourceManager.GetString("ResetAlreadyRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link has expired..
        /// </summary>
        public static string ResetPasswordLinkExpired {
            get {
                return ResourceManager.GetString("ResetPasswordLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset password token is valid..
        /// </summary>
        public static string ResetPasswordTokenValid {
            get {
                return ResourceManager.GetString("ResetPasswordTokenValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token and refresh token are required..
        /// </summary>
        public static string TokenAndRefreshRequired {
            get {
                return ResourceManager.GetString("TokenAndRefreshRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token format is invalid or corrupted..
        /// </summary>
        public static string TokenFormatInvalid {
            get {
                return ResourceManager.GetString("TokenFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid or has already been used..
        /// </summary>
        public static string TokenInvalidOrUsed {
            get {
                return ResourceManager.GetString("TokenInvalidOrUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token mismatch or already used..
        /// </summary>
        public static string TokenMismatch {
            get {
                return ResourceManager.GetString("TokenMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed successfully..
        /// </summary>
        public static string TokenRefreshedSuccessfully {
            get {
                return ResourceManager.GetString("TokenRefreshedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token timestamp is invalid..
        /// </summary>
        public static string TokenTimestampInvalid {
            get {
                return ResourceManager.GetString("TokenTimestampInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token validation failed..
        /// </summary>
        public static string TokenValidationFailed {
            get {
                return ResourceManager.GetString("TokenValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data cannot be null..
        /// </summary>
        public static string UpdateDataRequired {
            get {
                return ResourceManager.GetString("UpdateDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no photo to delete..
        /// </summary>
        public static string UserHasNoPhotoToDelete {
            get {
                return ResourceManager.GetString("UserHasNoPhotoToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId and token are required..
        /// </summary>
        public static string UserIdAndTokenRequired {
            get {
                return ResourceManager.GetString("UserIdAndTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the provided ID does not exist..
        /// </summary>
        public static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User photo deleted successfully..
        /// </summary>
        public static string UserPhotoDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserPhotoDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User photo uploaded successfully..
        /// </summary>
        public static string UserPhotoUploadedSuccessfully {
            get {
                return ResourceManager.GetString("UserPhotoUploadedSuccessfully", resourceCulture);
            }
        }
    }
}
