//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.Services.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserManagementService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserManagementService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.Services.Account.UserManagementService", typeof(UserManagementService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin created successfully..
        /// </summary>
        public static string AdminCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AdminCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin deleted successfully..
        /// </summary>
        public static string AdminDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AdminDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins cannot activate Admins or SuperAdmins..
        /// </summary>
        public static string AdminsCannotActivateAdmin {
            get {
                return ResourceManager.GetString("AdminsCannotActivateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins cannot deactivate Admins or SuperAdmins..
        /// </summary>
        public static string AdminsCannotDeactivateAdmin {
            get {
                return ResourceManager.GetString("AdminsCannotDeactivateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins cannot delete Admins or SuperAdmins..
        /// </summary>
        public static string AdminsCannotDeleteAdmin {
            get {
                return ResourceManager.GetString("AdminsCannotDeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate user..
        /// </summary>
        public static string FailedToActivateUser {
            get {
                return ResourceManager.GetString("FailedToActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign role..
        /// </summary>
        public static string FailedToAssignRole {
            get {
                return ResourceManager.GetString("FailedToAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create admin..
        /// </summary>
        public static string FailedToCreateAdmin {
            get {
                return ResourceManager.GetString("FailedToCreateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deactivate user..
        /// </summary>
        public static string FailedToDeactivateUser {
            get {
                return ResourceManager.GetString("FailedToDeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete admin..
        /// </summary>
        public static string FailedToDeleteAdmin {
            get {
                return ResourceManager.GetString("FailedToDeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user..
        /// </summary>
        public static string FailedToDeleteUser {
            get {
                return ResourceManager.GetString("FailedToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove role..
        /// </summary>
        public static string FailedToRemoveRole {
            get {
                return ResourceManager.GetString("FailedToRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Admin or Super Admin can delete a user..
        /// </summary>
        public static string OnlyAdminCanDeleteUser {
            get {
                return ResourceManager.GetString("OnlyAdminCanDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a Super Admin can delete an Admin..
        /// </summary>
        public static string OnlySuperAdminCanDeleteAdmin {
            get {
                return ResourceManager.GetString("OnlySuperAdminCanDeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a Super Admin can delete another Super Admin..
        /// </summary>
        public static string OnlySuperAdminCanDeleteSuperAdmin {
            get {
                return ResourceManager.GetString("OnlySuperAdminCanDeleteSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role assigned successfully..
        /// </summary>
        public static string RoleAssignedSuccessfully {
            get {
                return ResourceManager.GetString("RoleAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role removed successfully..
        /// </summary>
        public static string RoleRemovedSuccessfully {
            get {
                return ResourceManager.GetString("RoleRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmins cannot activate other SuperAdmins..
        /// </summary>
        public static string SuperAdminsCannotActivateSuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdminsCannotActivateSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmins cannot deactivate other SuperAdmins..
        /// </summary>
        public static string SuperAdminsCannotDeactivateSuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdminsCannotDeactivateSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmins cannot delete other SuperAdmins..
        /// </summary>
        public static string SuperAdminsCannotDeleteSuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdminsCannotDeleteSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User activated successfully..
        /// </summary>
        public static string UserActivatedSuccessfully {
            get {
                return ResourceManager.GetString("UserActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deactivated successfully..
        /// </summary>
        public static string UserDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
