<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EStoreX.API</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>E-StoreX.API.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Images\AppleIPhone16ProMaxSingleSIM256GB\8GB - 6.9 5G Mobile Phone - Desert Titanium\**" />
    <Content Remove="wwwroot\Images\AppleIPhone16ProMaxSingleSIM256GB\8GB - 6.9 5G Mobile Phone - Desert Titanium\**" />
    <EmbeddedResource Remove="wwwroot\Images\AppleIPhone16ProMaxSingleSIM256GB\8GB - 6.9 5G Mobile Phone - Desert Titanium\**" />
    <None Remove="wwwroot\Images\AppleIPhone16ProMaxSingleSIM256GB\8GB - 6.9 5G Mobile Phone - Desert Titanium\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="8.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-StoreX.Core\E-StoreX.Core.csproj" />
    <ProjectReference Include="..\E-StoreX.Infrastructure\E-StoreX.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\SharedResource.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SharedResource.ar.resx" />
  </ItemGroup>

</Project>
