//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.Services.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrandService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrandService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.Services.Products.BrandService", typeof(BrandService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brand with the name &apos;{0}&apos; already exists..
        /// </summary>
        public static string BrandAlreadyExists {
            get {
                return ResourceManager.GetString("BrandAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand ID cannot be empty..
        /// </summary>
        public static string BrandIdRequired {
            get {
                return ResourceManager.GetString("BrandIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand name cannot be null or empty..
        /// </summary>
        public static string BrandNameRequired {
            get {
                return ResourceManager.GetString("BrandNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand not found..
        /// </summary>
        public static string BrandNotFound {
            get {
                return ResourceManager.GetString("BrandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand with ID {0} not found..
        /// </summary>
        public static string BrandNotFoundWithId {
            get {
                return ResourceManager.GetString("BrandNotFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images updated successfully..
        /// </summary>
        public static string ImagesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ImagesUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name cannot be null or empty..
        /// </summary>
        public static string NewBrandNameRequired {
            get {
                return ResourceManager.GetString("NewBrandNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files provided..
        /// </summary>
        public static string NoFilesProvided {
            get {
                return ResourceManager.GetString("NoFilesProvided", resourceCulture);
            }
        }
    }
}
