//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.Services.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductsService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductsService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.Services.Products.ProductsService", typeof(ProductsService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best sellers retrieved successfully..
        /// </summary>
        public static string BestSellersRetrieved {
            get {
                return ResourceManager.GetString("BestSellersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count must be greater than zero..
        /// </summary>
        public static string CountMustBePositive {
            get {
                return ResourceManager.GetString("CountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images updated successfully..
        /// </summary>
        public static string ImagesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ImagesUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files provided..
        /// </summary>
        public static string NoFilesProvided {
            get {
                return ResourceManager.GetString("NoFilesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found..
        /// </summary>
        public static string NoProductsFound {
            get {
                return ResourceManager.GetString("NoProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID cannot be empty..
        /// </summary>
        public static string ProductIdRequired {
            get {
                return ResourceManager.GetString("ProductIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with ID {0} not found..
        /// </summary>
        public static string ProductNotFoundWithId {
            get {
                return ResourceManager.GetString("ProductNotFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product request cannot be null..
        /// </summary>
        public static string ProductRequestRequired {
            get {
                return ResourceManager.GetString("ProductRequestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product update request cannot be null..
        /// </summary>
        public static string ProductUpdateRequestRequired {
            get {
                return ResourceManager.GetString("ProductUpdateRequestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query cannot be null..
        /// </summary>
        public static string QueryRequired {
            get {
                return ResourceManager.GetString("QueryRequired", resourceCulture);
            }
        }
    }
}
