//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.DTO.Basket {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BasketValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasketValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.DTO.Basket.BasketValidationMessages", typeof(BasketValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be a valid URL..
        /// </summary>
        public static string InvalidImageUrl {
            get {
                return ResourceManager.GetString("InvalidImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than 0..
        /// </summary>
        public static string InvalidPriceMin {
            get {
                return ResourceManager.GetString("InvalidPriceMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be at least 1..
        /// </summary>
        public static string InvalidQuantityMin {
            get {
                return ResourceManager.GetString("InvalidQuantityMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthBasketDescription {
            get {
                return ResourceManager.GetString("MaxLengthBasketDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthBasketName {
            get {
                return ResourceManager.GetString("MaxLengthBasketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket ID is required..
        /// </summary>
        public static string RequiredBasketId {
            get {
                return ResourceManager.GetString("RequiredBasketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket item is required..
        /// </summary>
        public static string RequiredBasketItem {
            get {
                return ResourceManager.GetString("RequiredBasketItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string RequiredBasketName {
            get {
                return ResourceManager.GetString("RequiredBasketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required..
        /// </summary>
        public static string RequiredCategory {
            get {
                return ResourceManager.GetString("RequiredCategory", resourceCulture);
            }
        }
    }
}
