<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>EStoreX.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.GitHub" Version="8.3.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="EPPlus" Version="8.1.0" />
    <PackageReference Include="Hangfire" Version="1.8.21" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
    <PackageReference Include="Hangfire.Console" Version="1.4.3" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.21" />
    <PackageReference Include="itext7" Version="8.0.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.0" />
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MimeKit" Version="4.15.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
    <PackageReference Include="Stripe.net" Version="45.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\DTO\Account\AuthValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AuthValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Basket\BasketValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BasketValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Categories\CategoryValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CategoryValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Common\CommonValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommonValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Discount\DiscountValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DiscountValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Orders\OrderValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OrderValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Products\ProductValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DTO\Ratings\RatingValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RatingValidationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Account\AuthenticationService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AuthenticationService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Account\UserManagementService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserManagementService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Categories\CategoriesService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CategoriesService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Common\EmailSenderService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailSenderService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Common\EmailTemplateService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailTemplateService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Common\EntityImageManager.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EntityImageManager.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Common\ImageService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ImageService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Common\JwtService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>JwtService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Common\PaymentService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PaymentService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Discounts\DiscountService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DiscountService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Favourites\FavouriteService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FavouriteService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Orders\OrderService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OrderService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Products\BrandService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BrandService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Products\ProductsService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductsService.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Services\Ratings\RatingService.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RatingService.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\DTO\Account\AuthValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AuthValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Basket\BasketValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BasketValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Categories\CategoryValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CategoryValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Common\CommonValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CommonValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Discount\DiscountValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DiscountValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Orders\OrderValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OrderValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Products\ProductValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DTO\Ratings\RatingValidationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RatingValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Account\AuthenticationService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AuthenticationService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Account\UserManagementService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UserManagementService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Categories\CategoriesService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CategoriesService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Common\EmailSenderService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EmailSenderService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Common\EmailTemplateService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EmailTemplateService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Common\EntityImageManager.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EntityImageManager.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Common\ImageService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ImageService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Common\JwtService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>JwtService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Common\PaymentService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PaymentService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Discounts\DiscountService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DiscountService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Favourites\FavouriteService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>FavouriteService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Orders\OrderService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OrderService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Products\BrandService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BrandService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Products\ProductsService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductsService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Services\Ratings\RatingService.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RatingService.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
