//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.Services.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplateService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplateService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.Services.Common.EmailTemplateService", typeof(EmailTemplateService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing up with &lt;strong&gt;E-StoreX&lt;/strong&gt;. Click the button below to confirm your email address and get started:.
        /// </summary>
        public static string Confirmation_Body {
            get {
                return ResourceManager.GetString("Confirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string Confirmation_Button {
            get {
                return ResourceManager.GetString("Confirmation_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there,.
        /// </summary>
        public static string Confirmation_Hi {
            get {
                return ResourceManager.GetString("Confirmation_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn’t create this account, you can safely ignore this email..
        /// </summary>
        public static string Confirmation_Ignore {
            get {
                return ResourceManager.GetString("Confirmation_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email.
        /// </summary>
        public static string Confirmation_Subject {
            get {
                return ResourceManager.GetString("Confirmation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email.
        /// </summary>
        public static string Confirmation_Title {
            get {
                return ResourceManager.GetString("Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message was sent from the E-StoreX contact form..
        /// </summary>
        public static string ContactMessage_Footer {
            get {
                return ResourceManager.GetString("ContactMessage_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string ContactMessage_Table_Email {
            get {
                return ResourceManager.GetString("ContactMessage_Table_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ContactMessage_Table_Name {
            get {
                return ResourceManager.GetString("ContactMessage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string ContactMessage_Table_Subject {
            get {
                return ResourceManager.GetString("ContactMessage_Table_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact Message.
        /// </summary>
        public static string ContactMessage_Title {
            get {
                return ResourceManager.GetString("ContactMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t miss this limited-time offer. Use the code at checkout and enjoy your savings 🚀.
        /// </summary>
        public static string Discount_Body {
            get {
                return ResourceManager.GetString("Discount_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},.
        /// </summary>
        public static string Discount_Hi {
            get {
                return ResourceManager.GetString("Discount_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a valued member of &lt;strong&gt;E-StoreX&lt;/strong&gt;, we’re excited to offer you a special discount!.
        /// </summary>
        public static string Discount_Intro {
            get {
                return ResourceManager.GetString("Discount_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Now.
        /// </summary>
        public static string Discount_ShopNow {
            get {
                return ResourceManager.GetString("Discount_ShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔥 Exclusive Discount Just for You!.
        /// </summary>
        public static string Discount_Subject {
            get {
                return ResourceManager.GetString("Discount_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Discount for You 🎉.
        /// </summary>
        public static string Discount_Title {
            get {
                return ResourceManager.GetString("Discount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until: {0}.
        /// </summary>
        public static string Discount_ValidUntil {
            get {
                return ResourceManager.GetString("Discount_ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} E-StoreX. Developed by Ibrahim Hassan..
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re thrilled to share the latest updates and highlights from &lt;strong&gt;E-StoreX&lt;/strong&gt; this week..
        /// </summary>
        public static string Newsletter_Body {
            get {
                return ResourceManager.GetString("Newsletter_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, 👋.
        /// </summary>
        public static string Newsletter_Greeting {
            get {
                return ResourceManager.GetString("Newsletter_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤝 Thanks for being part of our growing community!.
        /// </summary>
        public static string Newsletter_Highlight_Community {
            get {
                return ResourceManager.GetString("Newsletter_Highlight_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌟 Exciting new features are coming soon to improve your experience..
        /// </summary>
        public static string Newsletter_Highlight_Features {
            get {
                return ResourceManager.GetString("Newsletter_Highlight_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡ Faster performance &amp; smoother navigation across the platform..
        /// </summary>
        public static string Newsletter_Highlight_Performance {
            get {
                return ResourceManager.GetString("Newsletter_Highlight_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dashboard.
        /// </summary>
        public static string Newsletter_OpenDashboard {
            get {
                return ResourceManager.GetString("Newsletter_OpenDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tuned — more updates, tips, and exclusive insights are on the way 🚀.
        /// </summary>
        public static string Newsletter_StayTuned {
            get {
                return ResourceManager.GetString("Newsletter_StayTuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Your Weekly E-StoreX Highlights Are Here!.
        /// </summary>
        public static string Newsletter_Subject {
            get {
                return ResourceManager.GetString("Newsletter_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-StoreX Weekly Newsletter.
        /// </summary>
        public static string Newsletter_Title {
            get {
                return ResourceManager.GetString("Newsletter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method:.
        /// </summary>
        public static string OrderConfirmation_DeliveryMethod {
            get {
                return ResourceManager.GetString("OrderConfirmation_DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount:.
        /// </summary>
        public static string OrderConfirmation_Discount {
            get {
                return ResourceManager.GetString("OrderConfirmation_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},.
        /// </summary>
        public static string OrderConfirmation_Hi {
            get {
                return ResourceManager.GetString("OrderConfirmation_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID:.
        /// </summary>
        public static string OrderConfirmation_OrderID {
            get {
                return ResourceManager.GetString("OrderConfirmation_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been successfully placed on &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string OrderConfirmation_PlacedOn {
            get {
                return ResourceManager.GetString("OrderConfirmation_PlacedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, just reply to this email — we’re happy to help!.
        /// </summary>
        public static string OrderConfirmation_Questions {
            get {
                return ResourceManager.GetString("OrderConfirmation_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address:.
        /// </summary>
        public static string OrderConfirmation_ShippingAddress {
            get {
                return ResourceManager.GetString("OrderConfirmation_ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛒 Order Confirmation - E-StoreX.
        /// </summary>
        public static string OrderConfirmation_Subject {
            get {
                return ResourceManager.GetString("OrderConfirmation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string OrderConfirmation_Table_Image {
            get {
                return ResourceManager.GetString("OrderConfirmation_Table_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string OrderConfirmation_Table_Price {
            get {
                return ResourceManager.GetString("OrderConfirmation_Table_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string OrderConfirmation_Table_Product {
            get {
                return ResourceManager.GetString("OrderConfirmation_Table_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string OrderConfirmation_Table_Qty {
            get {
                return ResourceManager.GetString("OrderConfirmation_Table_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order!.
        /// </summary>
        public static string OrderConfirmation_Title {
            get {
                return ResourceManager.GetString("OrderConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string OrderConfirmation_Total {
            get {
                return ResourceManager.GetString("OrderConfirmation_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to reset the password for your E-StoreX account. Click the button below to continue:.
        /// </summary>
        public static string PasswordReset_Body {
            get {
                return ResourceManager.GetString("PasswordReset_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string PasswordReset_Button {
            get {
                return ResourceManager.GetString("PasswordReset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn’t request a password reset, you can safely ignore this email. This link is valid for 10 minutes..
        /// </summary>
        public static string PasswordReset_Ignore {
            get {
                return ResourceManager.GetString("PasswordReset_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string PasswordReset_Subject {
            get {
                return ResourceManager.GetString("PasswordReset_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string PasswordReset_Title {
            get {
                return ResourceManager.GetString("PasswordReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment for order &lt;strong&gt;#{0}&lt;/strong&gt; on &lt;strong&gt;{1}&lt;/strong&gt; did not go through..
        /// </summary>
        public static string PaymentFailed_Body {
            get {
                return ResourceManager.GetString("PaymentFailed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the issue persists, please contact our support team and we’ll be happy to help you..
        /// </summary>
        public static string PaymentFailed_ContactSupport {
            get {
                return ResourceManager.GetString("PaymentFailed_ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, {0}..
        /// </summary>
        public static string PaymentFailed_Hi {
            get {
                return ResourceManager.GetString("PaymentFailed_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your payment details and try again, or use a different payment method..
        /// </summary>
        public static string PaymentFailed_Retry {
            get {
                return ResourceManager.GetString("PaymentFailed_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Payment Failed - E-StoreX.
        /// </summary>
        public static string PaymentFailed_Subject {
            get {
                return ResourceManager.GetString("PaymentFailed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string PaymentFailed_Summary {
            get {
                return ResourceManager.GetString("PaymentFailed_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Failed ❌.
        /// </summary>
        public static string PaymentFailed_Title {
            get {
                return ResourceManager.GetString("PaymentFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please find attached the sales report for the period:.
        /// </summary>
        public static string SalesReport_Body {
            get {
                return ResourceManager.GetString("SalesReport_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download and review the Excel file attached below..
        /// </summary>
        public static string SalesReport_Download {
            get {
                return ResourceManager.GetString("SalesReport_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string SalesReport_From {
            get {
                return ResourceManager.GetString("SalesReport_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Admin,.
        /// </summary>
        public static string SalesReport_Greeting {
            get {
                return ResourceManager.GetString("SalesReport_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈 Daily Sales Report ({0}).
        /// </summary>
        public static string SalesReport_Subject {
            get {
                return ResourceManager.GetString("SalesReport_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Daily Sales Report.
        /// </summary>
        public static string SalesReport_Title {
            get {
                return ResourceManager.GetString("SalesReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string SalesReport_To {
            get {
                return ResourceManager.GetString("SalesReport_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is happening behind closed doors at &lt;strong&gt;E-StoreX&lt;/strong&gt;. We aren&apos;t ready to show the world yet, but we wanted &lt;strong&gt;you&lt;/strong&gt; to be the first to know that it&apos;s coming..
        /// </summary>
        public static string Teaser_Body {
            get {
                return ResourceManager.GetString("Teaser_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string Teaser_ComingSoon {
            get {
                return ResourceManager.GetString("Teaser_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-StoreX Mystery Launch.
        /// </summary>
        public static string Teaser_FooterBrand {
            get {
                return ResourceManager.GetString("Teaser_FooterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated by Ibrahim Hassan.
        /// </summary>
        public static string Teaser_FooterCuratedBy {
            get {
                return ResourceManager.GetString("Teaser_FooterCuratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shhh... It&apos;s a Secret. 😉.
        /// </summary>
        public static string Teaser_Headline {
            get {
                return ResourceManager.GetString("Teaser_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},.
        /// </summary>
        public static string Teaser_Hi {
            get {
                return ResourceManager.GetString("Teaser_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spoilers. No leaks.&lt;br&gt;Just greatness..
        /// </summary>
        public static string Teaser_MysteryText {
            get {
                return ResourceManager.GetString("Teaser_MysteryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Ready.
        /// </summary>
        public static string Teaser_ReadyBtn {
            get {
                return ResourceManager.GetString("Teaser_ReadyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this email safe. You’ll need it when the clock hits zero..
        /// </summary>
        public static string Teaser_SafeEmail {
            get {
                return ResourceManager.GetString("Teaser_SafeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shhh... It&apos;s a Secret 😉.
        /// </summary>
        public static string Teaser_Subject {
            get {
                return ResourceManager.GetString("Teaser_Subject", resourceCulture);
            }
        }
    }
}
