//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreX.Core.Resources.DTO.Discount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiscountValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiscountValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EStoreX.Core.Resources.DTO.Discount.DiscountValidationMessages", typeof(DiscountValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max usage count must be at least 1..
        /// </summary>
        public static string InvalidMaxUsageCount {
            get {
                return ResourceManager.GetString("InvalidMaxUsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage must be between 0 and 100..
        /// </summary>
        public static string InvalidPercentageRange {
            get {
                return ResourceManager.GetString("InvalidPercentageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandId is required when DiscountType is Brand..
        /// </summary>
        public static string RequiredBrandIdForType {
            get {
                return ResourceManager.GetString("RequiredBrandIdForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId is required when DiscountType is Category..
        /// </summary>
        public static string RequiredCategoryIdForType {
            get {
                return ResourceManager.GetString("RequiredCategoryIdForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount type is required..
        /// </summary>
        public static string RequiredDiscountType {
            get {
                return ResourceManager.GetString("RequiredDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId is required when DiscountType is Product..
        /// </summary>
        public static string RequiredProductIdForType {
            get {
                return ResourceManager.GetString("RequiredProductIdForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required..
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
    }
}
